### ISSUE TITLE
مشکل در css سایت

### ISSUE THREAD

**Issue by ShahriarKh** [amir2mi/vajehh#6]
```css
.main-container {
    max-width: 1366px;
}
```
باعث شده gradient توی homepage برای مانیتور‌های بزرگ ناقص باشه. می‌شه حذفش کرد.
